### ISSUE TITLE
No way to add patient in mobile view 

### ISSUE THREAD

**Issue by kylegoodwin** [uwcirg/tb-mobile-app#392]
## Task Breakdown

These aren't necessarily in the best order, might want to think through it a bit first.

- [ ] Check out the new UI & component for adding an appointment to get a feel for how this should look 
    - Scroll down to the bottom of the patient home page and tap "Add Appointment"
    - Component is located here src/Components/Shared/Appointments
    - Check out the state management / using the useAsync hook to submit the data to the API
    - Having a page to show success vs error and any error message would be good, the useAsync hook makes this easy
- [x] Add a function in the src/API/PractitionerAPI.js file that connects to the API route for adding a patient
   - Check out the implementation of the appointments for clues here
   -    ` {
            givenName: Firstname
            familyName: Lastname
            phoneNumber: 123456789
            treatmentStart: DateTime.local().toISO(), ( any iso datetime )
        },`
  - For now will be a POST to /patients with this body:
- [x] Add a route in the src/Practitioner/Routes.js for /add-patient

   - Hoping to add a v2 api route for this before we push this out
- [x] On the provider side tasks page ( homepage with list of patients ) add a button next to the search button
    - [x] This should be an MUI IconButton, and use a react-router Link to go to /add-patient
- [x] Create a new component src/Practitioner/AddPatient.js
    - UI reference shown below
    - Use the shared topbar component that we have been using (PageLabel)
    - The old component for doing this is located in src/Practitioner/CohortView/AddPatient if you want to take a look
    - To simplify things here, we will not use the Mobx stores, and just store the state locally 
- [x] Refactor new input cards UI to share across the app
    - I implemented the card and input components for the add appointment functionality recently, these can be refactored to share across the UI  
    - ie. Factor out this component src/Components/Shared/Appointments/AddAppointment/InputCard.js

## UI Example

( Just the right side here is relevant )

![image](https://user-images.githubusercontent.com/10137989/172414354-797e1a81-ad00-4184-868c-503b423e6814.png)

**Comment by kylegoodwin** [comment]
Nice work so far John!

Reviewed the code and found a few more things that need to be added:

- [ ] Make the button to add a patient have a Colors.buttonBlue background color, and white content color
- [ ] Success screen has success message for adding an appointment, add better text here
- [ ] Remove option to "add another patient" since this is not really important to the adding patient flow
- [ ] Success screen should show the activation code for the patient
- [ ] Error page will only show if there is a pretty bad error on the server, there should be a message about contacting us there
