### ISSUE TITLE
Chunk patients on provider task list by issue status

### ISSUE THREAD

**Issue by kylegoodwin** [uwcirg/tb-mobile-app#421]
- [x] Label top section with "Has Issues"
- [x] Label bottom section with "No Issues Reported"
- [x] Change the handling of cards when no issues are present, don't allow expansion
