### ISSUE TITLE
Display message to user when no patients are shown in the currently selected list

### ISSUE THREAD

**Issue by kylegoodwin** [uwcirg/tb-mobile-app#446]
## Todo
- [x] Add code to check if there is an empty list of patients on each tab
- [x] Refactor ```src/Practitioner/ReviewPatients/LoadingPatients.js``` to share a message with a similar look across all of the different states listed below
    - [x] Keep the picture but change the text and conditionally render the loading circle only for the loading state
    - [x] States will be:
        - [x] Loading list of patients to review ( you can keep this the same for now )
        - [x] Empty first tab: message saying that there are no patients left to review
        - [x] Empty second tab: message saying that no patients have been reviewed yet today
        - [x] Empty third tab: message about no patients yet added to app

## Current State:

Loading Screen ( keep this the same )
<img width="385" alt="Screen Shot 2022-07-27 at 2 57 55 PM" src="https://user-images.githubusercontent.com/10137989/181350985-fa504218-f69e-47c6-bdd2-724d010a274e.png">

Empty list where message should go:
<img width="388" alt="Screen Shot 2022-07-27 at 3 04 41 PM" src="https://user-images.githubusercontent.com/10137989/181352161-713a33ed-fd6e-4cd2-924b-7d2d36a25804.png">
