### ISSUE TITLE
Fix patient issue list to reflect new reports

### ISSUE THREAD

**Issue by johnny2smooth** [uwcirg/tb-mobile-app#465]
# Description

This to-do was raised to make sure that patient issue data was being updated more often than daily, if a patient ended up having an issue after the initial list was created resolved.

# To-do

- [x]  Modify alreadyReviewed logic on front end to further specify requirements
- [x]  instead of checking wasToday we can check that this **last general resolution** was created after their last report.
- [x]  Add logic (+maybe other checks) to verify there aren't any new reports since **last general resolution**
- [x]  Sync up logic with current components <ListOfPatients /> and <AllPatientsList />
- [x] unresolvedReports.createdAt time is not changing! even when a new update + message is made
- [x] Reviewed patient with initial problem repopulates to unreviewed upon reload.
- [x]  Rename ^^ and refactor

# Screenshots

Upon patient resolution, the resolutions API is updated. It is being sent twice as an OPTIONS and a POST method.

![Image](https://user-images.githubusercontent.com/54085506/188918824-ff0d4375-730d-4fb1-9232-9341b6b3b1b7.png)

Notice here how there is no API request to update the list of patient_issues. 

When this page is reloaded, we see that all of the original patient_issues data is being sent. None of the previous interactions have changed its shape. 

![Image](https://user-images.githubusercontent.com/54085506/188918867-fdf23738-0491-4808-8f32-7f6f941a303e.png)

I am curious as to how the page knows how to not render all the issues from the API

## New understanding
